### PR TITLE
Add configuration options for OPC sampling and publishing, use OPC subscriptions, change config file syntax

### PR DESCRIPTION
**Pull request by hansgschossmann**
this PR will allow to configure OPC sampling and publishing intervals for the published nodes, it creates for each publishing interval a separate subscription to the OPC server, the syntax to configure the notes to publish has changed and several bugs have been fixed.

### CODE REVIEW

**Comment by hansgschossmann** [comment]
there is one more change, which should go with it.

**Comment by hansgschossmann** [comment]
closed too early, the change was automatically picked up:)

**Comment by khilscher** [comment]
@hansgschossmann do you want to also include in the PR the corresponding updates to the README explaining the new settings and example publishednodes.json?

**Comment by hansgschossmann** [comment]
Yes, i will document this and all other changes. For now, pls take a look at the publishednodes.json in the repo. I have added comments there.

**Comment by hansgschossmann** [comment]
the publish/unpublish integration needs to be rewritten.

**Pull request closed without merging**
